{{ if and (eq .Values.config.createSecrets true) (gt (len (.Files.Glob "secrets/additional-cas/**")) 0) }}
apiVersion: v1
stringData:
  {{- range $path, $content := .Files.Glob "secrets/additional-cas/**" }}
  {{ base $path }}: |
    {{- $content | toString | nindent 4 }}{{ end }}
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: stackrox
  name: additional-ca-sensor
  namespace: stackrox
type: Opaque
{{ end }}
