{{ if eq .Values.config.createUpgraderServiceAccount true}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sensor-upgrader
  namespace: stackrox
  labels:
    app.kubernetes.io/name: stackrox
imagePullSecrets:
- name: stackrox
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:upgrade-sensors
  labels:
    app.kubernetes.io/name: stackrox
subjects:
- kind: ServiceAccount
  name: sensor-upgrader
  namespace: stackrox
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
{{ end }}