cluster:
  name: 
  type: KUBERNETES_CLUSTER

endpoint:
  central: central.stackrox:443
  advertised: sensor.stackrox:443

image:
  repository:
    main: main
    collector: collector
  registry:
    main: stackrox.io
    collector: collector.stackrox.io

config:
  collectionMethod: KERNEL_MODULE
  admissionControl:
    createService: false
    listenOnUpdates: false
    enableService: false
    enforceOnUpdates: false
    scanInline: false
    disableBypass: false
    timeout: 3
  registryOverride:
  disableTaintTolerations: true
  createUpgraderServiceAccount: false
  createSecrets: true
  offlineMode: false
  slimCollector: false

envVars:  []
  

