{{- include "srox.init" . -}}

{{- if ._rox.central.persistence._pvcCfg }}
{{- if ._rox.central.persistence._pvcCfg.storageClass -}}
{{- if eq ._rox.central.persistence._pvcCfg.storageClass "stackrox-gke-ssd" }}
{{- $lookupOut := dict -}}
{{- $_ := include "srox.safeLookup" (list . $lookupOut "storage.k8s.io/v1" "StorageClass" "" "stackrox-gke-ssd") -}}
{{- if and (not $lookupOut.result) (or .Release.IsInstall $lookupOut.reliable) (not ._rox.meta.noCreateStorageClass) -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "stackrox-gke-ssd"
  labels:
    {{- include "srox.labels" (list . "storageclass" "stackrox-gke-ssd") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "storageclass" "stackrox-gke-ssd") | nindent 4 }}
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/resource-policy": keep
    "helm.sh/hook-delete-policy": never
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
{{- end -}}
{{- end }}
{{- end -}}
{{- end }}
